CREATE TABLE "CONTACT"(ID int NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), FIRSTNAME varchar(50) NOT NULL, LASTNAME varchar(50) NOT NULL, EMAIL varchar(50) NOT NULL UNIQUE)
CREATE UNIQUE INDEX SQL_CONTACT_ID_INDEX ON "CONTACT"(ID)
CREATE UNIQUE INDEX SQL_CONTACT_EMAIL_INDEX ON "CONTACT"(EMAIL)

