CREATE TABLE "USER"(ID int NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), USERNAME varchar(50) NOT NULL UNIQUE, GROUPNAME varchar(50) NOT NULL, PASSWORD varchar(50) NOT NULL)
CREATE UNIQUE INDEX SQL_USER_ID_INDEX ON "USER"(ID)
CREATE UNIQUE INDEX SQL_USER_USERNAME_INDEX ON "USER"(USERNAME)

CREATE TABLE "CONTACT"(ID int NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), FIRSTNAME varchar(50) NOT NULL, LASTNAME varchar(50) NOT NULL, EMAIL varchar(50) NOT NULL, USER_ID int NOT NULL)
ALTER TABLE "CONTACT" ADD CONSTRAINT FK_CONTACT_USER_ID FOREIGN KEY (USER) REFERENCES "USER"(ID)
CREATE UNIQUE INDEX SQL_CONTACT_ID_INDEX ON "CONTACT"(ID)

